### ISSUE TITLE
Erro ao tentar criar empréstimo com algo que não seja um e-mail cadastrado

### ISSUE THREAD

**Issue by brunnogomes** [hent-dev/full-stack-challenge#2]
Se digitar qualquer coisa no campo e-mail a aplicação dá erro 500.

![Captura de Tela 2021-11-22 às 13 48 27](https://user-images.githubusercontent.com/190953/142901866-adc0fef5-d723-4246-98f5-e69070bcc843.png)

**Comment by kinhosz** [comment]
Consertado e deployado!
